### ISSUE TITLE
Warnung bei KEYMATIC

### ISSUE THREAD

**Issue by Hypnos3** [HM-RedMatic/node-red-contrib-ccu#40]
Ist zwar nur eine Warnung, aber ich denke mal, eine Keymatic hat keine ON_TIME:
![image](https://user-images.githubusercontent.com/12692680/49612393-e662fd80-f9a4-11e8-880c-42c0cf620f7a.png)

unknown paramsetDescription BidCos-RF/HM-Sec-Key/2.5/7/KEYMATIC/VALUES ON_TIME

**Comment by hobbyquaker** [comment]
Sollte in 1.10.6 behoben sein. Allerdings müsstest Du die Config Deiner Keymatic (und eventueller anderer Value Nodes die das Problem haben) einmal aufmachen und auf done klicken damit die Konfiguration "bereinigt" wird.
