### ISSUE TITLE
node combine-statistic missing

### ISSUE THREAD

**Issue by cgatnet** [HM-RedMatic/node-red-contrib-ccu#42]
Hi, I just tried to import the first example from RedMatic Wiki (Anzahl und Liste offener Fenster im Dashboard anzeigen), but got the error message, that a node called "combine-statistic" is missing.
Cannot find this node anywhere. 
I am new to node-red, maybe I missed something? :o)
My imported flow now shows a unknown node.
Thanks for your support in advance!
Best regards,
Christian

**Comment by hobbyquaker** [comment]
These Nodes are shipped with RedMatic, if you're using node-red-contrib-ccu outside of RedMatic you have to install them manually: https://flows.nodered.org/node/node-red-contrib-combine

**Comment by cgatnet** [comment]
Ok, yes, that fixed my problem! Thanks for your quick reply!
