### ISSUE TITLE
Error: binrpc server close timeout

### ISSUE THREAD

**Issue by drMaxxi** [HM-RedMatic/node-red-contrib-ccu#43]
Danke für das Update! 2 der drei Fehlermeldungen sind nicht mehr aufgetreten. Es bleibt noch folgende:
Error: binrpc server close timeout

**Comment by hobbyquaker** [comment]
Den Fehler kannst ignorieren, sollte keine Auswirkungen haben. Werden den Timeout etwas verlängern in der Hoffnung dass das dann seltener passiert und die Meldung von Error auf Warning runterstufen.
