### ISSUE TITLE
Is the ccu node also working without redmatic

### ISSUE THREAD

**Issue by Marty56** [HM-RedMatic/node-red-contrib-ccu#45]
I am running node red on a separate device and would like to contect to standard ccu2.
Is this possible? I did not install the addon on this ccu because the ccu2 too weak to run node red.

When configuring the ccu it seems to recognize the IP of my ccu2 and also its name but then I am not sure what to enter for init address and listen address. I have entered the IP for my node red server and realized that I cannot not enter a listen address anymore. This field cannot be changed.

Also do I have to keep the port settings?
I have noticed from iobroker that my ccu normally listens on 2001 not the default ports 2061 for bin-rpc.

**Comment by hobbyquaker** [comment]
Yes, that's possible. You can leave the init address empty. Default port settings should be fine. These are not the Ports node-contrib-contrib-ccu is connecting to - these are the ports where node-red-contrib-ccu opens its own listeners.

**Comment by Marty56** [comment]
Thanks
