### ISSUE TITLE
Option "nur geänderte Werte" herausgeben, funktioniert nicht bei Fensterkontakten

### ISSUE THREAD

**Issue by Marty56** [HM-RedMatic/node-red-contrib-ccu#47]
Ich möchte, dass bei Änderung eines Fensterkontakts alle Mitglieder der Gruppe Fenster ihren Status übertragen. Das funktioniert beim Neustart von Node Red aber nicht mehr wenn ein Mitglied der Gruppe einen neuen Wert bekommt.
Die Option "nur geänderte Werte" ist nicht ausgewählt.

![bildschirmfoto 2018-12-28 um 12 42 23](https://user-images.githubusercontent.com/8623789/50514470-a8866000-0a9e-11e9-81d3-ce2f52305eaa.png)

**Comment by hobbyquaker** [comment]
Related: https://homematic-forum.de/forum/viewtopic.php?f=77&t=47893

**Comment by hobbyquaker** [comment]
Hier musst Du auf andere Methoden zurückgreifen, z.B. den Status im Context speichern. Den RPC Event Node so umzubauen dass bei jedem Event alle Datenpunkte auf die der Filter zutrifft ausgegeben werden halte ich für zu Aufwändig - v.a. da es andere Wege gibt das zu bewerkstelligen.
