### ISSUE TITLE
Keine Verbindung zu CCU3

### ISSUE THREAD

**Issue by pato-loco** [HM-RedMatic/node-red-contrib-ccu#65]
Hallo,

ich bin gerade von CCU2 auf CCU3 (pivCCU) umgestiegen. Bei der Gelegenheit möchte ich auch, dass Node-Red mit der CCU3 spricht.
Dafür habe ich node-red-contrib-ccu in Node-Red installiert. Node-Red befindet sich dabei nicht innerhalb des CCU3 Containers.
In der Node "value" habe ich dann die Verbindungsdaten zur CCU eingegeben und deployed. Allerdings kann ich nun unter Interfaces nichts auswählen.
Das DropDown Feld geht nicht mal auf. Es sieht so aus, wie wenn ich keine Verbindung zur CCU bekomme.

Kann mir bitte jemand helfen?

Vielen Dank schon mal!

**Comment by emeins** [comment]
Ja, hatte ich auch. Lag bei mir daran: https://github.com/HM-RedMatic/node-red-contrib-ccu/issues/60#issuecomment-460350753

**Comment by pato-loco** [comment]
Danke für die Rückmeldung. 

Bei der Standardinstallation ist dieser Part bereits enthalten. Daher behebt es meinen Fehler leider nicht.

**Comment by emeins** [comment]
Ich habe eigentlich genau die gleiche Konstellation laufen, piVCCU (CCU3) und Node Red. Das läuft soweit. Welche Versionen von NR und vom PlugIn verwendest Du?

Evtl. noch die Firewall-Einstellungen auf der CCU?

**Comment by pato-loco** [comment]
Hab den Fehler gefunden. In der Firewall war der Zugriff auf die beiden APIs nicht aktiviert und die Authentifizierung war nur mit Benutzername und Passwort erlaubt.
Jetzt geht es!
