### ISSUE TITLE
sysvar node: Output falsch

### ISSUE THREAD

**Issue by FordAndii** [HM-RedMatic/node-red-contrib-ccu#67]
Der Sysvar-Node bezieht sich auf eine Boolean-Variable. Die beiden Inject-Nodes sorgen dafür, dass die Systemvariable in der CCU auf true/false gesetzt wird:

![5](https://user-images.githubusercontent.com/48220859/54238968-30b2c800-451a-11e9-9943-3aec3ca55c50.png)

Allerdings stimmt der Output des Sysvar-Nodes nicht. Immer, wenn der Zustand der Variable von true auf false (oder umgekehrt) wechselt, besteht der Output des Sysvar-Nodes aus einem String mit dem aktuellen Timestamp. Erst wenn dann erneut derselbe Wert (true bzw. false) an den Sysvar-Node gesendet wird, gibt er den richtigen Wert (true bzw. false) aus.

**Comment by hobbyquaker** [comment]
@FordAndii Hmm, ich kann das nicht reproduzieren. Kannst Du mal bitte ein Screenshot der Variablenkonfiguration aus dem CCU WebUI zeigen und ein RedMatic Log (Loglevel Debug) anhängen? Auch interessant wäre der Output des Debug Nodes auf "complete msg object".

**Comment by FordAndii** [comment]
Ich konnte das Ganze auch mit einer anderen Variable reproduzieren. Definition der Variable:

![def](https://user-images.githubusercontent.com/48220859/54319522-07616d00-45ea-11e9-984d-d2bc277cbd27.PNG)

Debug-Node:

![debug](https://user-images.githubusercontent.com/48220859/54319527-0d574e00-45ea-11e9-81ff-5def74a6347b.PNG)

Welchen Teil des Logs brauchst du? Ich blicke da nicht ganz durch...

**Comment by hobbyquaker** [comment]
Habe da eine Vermutung, schau mal ob das Problem mit RedMatic 3.1.0 aus der Welt ist und gib bitte Bescheid.

**Comment by FordAndii** [comment]
Oh ja, das sieht sehr gut aus jetzt. Top! Besten Dank!
